<a href="https://colab.research.google.com/github/shivam003a/Machine-Learning/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# List in ML 1


In [2]:
list1 = [1,2,3,4]
print(list1)

[1, 2, 3, 4]


In [4]:
list2 = [1,2,3,'a']
print(list2)

[1, 2, 3, 'a']


In [7]:
list3 = [ i for i in range(10)]
print(list3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
list4 = [ [1,2,3] for i in range(5)]
print(list4)

[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [9]:
list5 = [ [j for j in range(5)] for i in range(5)]
print(list5)

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


In [12]:
list6 = [ [j+3*i for j in range(3)] for i in range(3)]
print(list6)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


# List in ML 2

In [18]:
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))

list7 = [ int(x) for x in input().split()]
print("List in 1D: ", list7)

list8 = []

for i in range(r):
  list8.append([])
  for j in range(c):
    list8[i].append(list7[c*i + j])

print("List in 2D: ", list8)

Enter number of rows: 2
Enter number of columns: 2
1 2 3 4
List in 1D:  [1, 2, 3, 4]
List in 2D:  [[1, 2], [3, 4]]


# Importing Library 

In [20]:
import math

x = math.gcd(120,45)
print(x)

15


In [22]:
import math as m

y = m.gcd(120,45)
print(y)

15


# Numpy


In [23]:
import numpy as np

In [25]:
demo = [1,2,3,4]
print("Demo List: ", demo)

np.array(demo)

Demo List:  [1, 2, 3, 4]


array([1, 2, 3, 4])

In [26]:
demo2 = [1,2,3,'Shivam']
np.array(demo2)

array(['1', '2', '3', 'Shivam'], dtype='<U21')

In [28]:
demo3 = np.zeros(3)
print(demo3)

demo4 = np.zeros(3, int)
print(demo4)

[0. 0. 0.]
[0 0 0]


In [29]:
demo3[1] = 'xyz'

ValueError: ignored

In [31]:
demo3[1] = "1"
print(demo3)

[0. 1. 0.]


In [32]:
demo3.dtype

dtype('float64')

In [36]:
demo5 = np.zeros((3,4))
print(demo5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
demo5[0][2] = '3'
print(demo5)

[[0. 0. 3. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
demo6 = np.zeros((3,4,5))
print(demo6)

demo6[1][1][2] = 1
print(demo6[1][1])

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[0. 0. 1. 0. 0.]


Slicing


In [41]:
demo6.shape

(3, 4, 5)

In [44]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [45]:
a[:, 1]

array([2, 5, 8])

In [46]:
a[1, :]

array([4, 5, 6])

# Operations in Numpy

In [47]:
x = [1,2,3]

x = x + 10

TypeError: ignored

In [49]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x = x+10
print(x)
print(x+y)

[11 12 13]
[15 17 19]


In [50]:
z = np.array([100,200,300,400])
print(x+z)

ValueError: ignored

In [51]:
print(x*2)
print(x*y)

[22 24 26]
[44 60 78]


In [53]:
print(x.mean())
print(x.sum())

12.0
36


In [60]:
# Distance between two point

p1 = np.array([2,2,2])
p2 = np.array([1,1,1])

var = ((p1-p2)**2).sum()
print(var)

# sum = var.sum()
# print(sum)

distance = m.sqrt(var)
print(distance)

3
1.7320508075688772


In [64]:
# dot product
m1 = np.array([1,2,3])
m2 = np.array([4,5,6])

print(m1.dot(m2))

32
